In [1]:
import pandas as pd

In [2]:
movies=pd.read_csv(r'C:\mini_proj\Movies_Rec\Top Indian Movies.csv')

In [3]:
movies.head(10)

,Title,Year of Release,Rating,Number of Reviews,Popularity Index,Movie Cast,Director,Description
0,Anbe Sivam,2003,8.7,21K,"11,629","['Kamal Haasan', 'Madhavan', 'Kiran Rathod', '...",Sundar C.,"Two men, one young and arrogant, the other dam..."
1,Golmaal,1979,8.5,19K,"39,634","['Amol Palekar', 'Bindiya Goswami', 'Deven Ver...",Hrishikesh Mukherjee,A man's simple lie to secure his job escalates...
2,Jai Bhim,2021,8.9,193K,898,"['Suriya', 'Lijo Mol Jose', 'Manikandan K.', '...",T.J. Gnanavel,When a tribal man is arrested for a case of al...
3,Nayakan,1987,8.6,20K,"17,539","['Kamal Haasan', 'Saranya Ponvannan', 'Delhi G...",Mani Ratnam,A common man's struggles against a corrupt pol...
4,Pariyerum Perumal,2018,8.7,16K,"17,434","['Kathir', 'Anandhi', 'Yogi Babu', 'Lijeesh', ...",Mari Selvaraj,A law student from a lower caste begins a frie...
5,Rocketry: The Nambi Effect,2022,9.2,18K,70,"['Madhavan', 'Simran', 'Rajit Kapoor', 'Ravi R...",Madhavan,Based on the life of ISRO Scientist Nambi Nara...
6,3 Idiots,2009,8.4,391K,875,"['Aamir Khan', 'Madhavan', 'Mona Singh', 'Shar...",Rajkumar Hirani,Two friends are searching for their long lost ...
7,Apur Sansar,1959,8.5,15K,"14,821","['Soumitra Chatterjee', 'Sharmila Tagore', 'Al...",Satyajit Ray,This final installment in Satyajit Ray's Apu T...
8,Manichitrathazhu,1993,8.7,11K,"32,603","['Shobana', 'Mohanlal', 'Suresh Gopi', 'Vinaya...",Fazil,When a forbidden room in an old bungalow is un...
9,Kumbalangi Nights,2019,8.5,15K,"12,316","['Shane Nigam', 'Soubin Shahir', 'Fahadh Faasi...",Madhu C. Narayanan,The film revolves around four brothers who sha...

In [4]:
movies.describe()

       Year of Release      Rating
count       250.000000  250.000000
mean       2008.068000    8.161200
std          14.198796    0.270754
min        1955.000000    7.700000
25%        2004.000000    8.000000
50%        2013.000000    8.100000
75%        2018.000000    8.300000
max        2022.000000    9.200000

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              250 non-null    object
 1   Year of Release    250 non-null    int64
 2   Rating             250 non-null    float64
 3   Number of Reviews  250 non-null    object
 4   Popularity Index   250 non-null    object
 5   Movie Cast         250 non-null    object
 6   Director           250 non-null    object
 7   Description        250 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 15.8+ KB

In [6]:
movies.isnull().sum()

Title                0
Year of Release      0
Rating               0
Number of Reviews    0
Popularity Index     0
Movie Cast           0
Director             0
Description          0
dtype: int64

Feature Selection Part

In [7]:
movies.columns

Index(['Title', 'Year of Release', 'Rating', 'Number of Reviews',
       'Popularity Index', 'Movie Cast', 'Director', 'Description'],
      dtype='object')

In [9]:
movies=movies[['Title', 'Movie Cast', 'Director','Description']]

In [10]:
movies

,Title,Movie Cast,Director,Description
0,Anbe Sivam,"['Kamal Haasan', 'Madhavan', 'Kiran Rathod', '...",Sundar C.,"Two men, one young and arrogant, the other dam..."
1,Golmaal,"['Amol Palekar', 'Bindiya Goswami', 'Deven Ver...",Hrishikesh Mukherjee,A man's simple lie to secure his job escalates...
2,Jai Bhim,"['Suriya', 'Lijo Mol Jose', 'Manikandan K.', '...",T.J. Gnanavel,When a tribal man is arrested for a case of al...
3,Nayakan,"['Kamal Haasan', 'Saranya Ponvannan', 'Delhi G...",Mani Ratnam,A common man's struggles against a corrupt pol...
4,Pariyerum Perumal,"['Kathir', 'Anandhi', 'Yogi Babu', 'Lijeesh', ...",Mari Selvaraj,A law student from a lower caste begins a frie...
...,...,...,...,...
245,24,"['Suriya', 'Samantha Ruth Prabhu', 'Nithya Men...",Vikram K. Kumar,"A scientist invents a time machine, which lead..."
246,Kapoor and Sons,"['Rishi Kapoor', 'Rajat Kapoor', 'Ratna Pathak...",Shakun Batra,The story about two brothers who visit their d...
247,Velaiilla Pattadhari,"['Dhanush', 'Saranya Ponvannan', 'Amala Paul',...",Velraj,A jobless young man gets to redeem himself.
248,Colour Photo,"['Suhas', 'Chandini Chowdary', 'Sunil', 'Harsh...",Sandeep Raj,A tragic-comedy that is set in the 90s between...
249,Rockstar,"['Ranbir Kapoor', 'Nargis Fakhri', 'Shammi Kap...",Imtiaz Ali,Janardhan Jakhar chases his dreams of becoming...

In [16]:
movies = movies.copy()
movies['tags'] = movies['Description'] + movies['Movie Cast']

In [17]:
movies

,Title,Movie Cast,Director,Description,tags
0,Anbe Sivam,"['Kamal Haasan', 'Madhavan', 'Kiran Rathod', '...",Sundar C.,"Two men, one young and arrogant, the other dam...","Two men, one young and arrogant, the other dam..."
1,Golmaal,"['Amol Palekar', 'Bindiya Goswami', 'Deven Ver...",Hrishikesh Mukherjee,A man's simple lie to secure his job escalates...,A man's simple lie to secure his job escalates...
2,Jai Bhim,"['Suriya', 'Lijo Mol Jose', 'Manikandan K.', '...",T.J. Gnanavel,When a tribal man is arrested for a case of al...,When a tribal man is arrested for a case of al...
3,Nayakan,"['Kamal Haasan', 'Saranya Ponvannan', 'Delhi G...",Mani Ratnam,A common man's struggles against a corrupt pol...,A common man's struggles against a corrupt pol...
4,Pariyerum Perumal,"['Kathir', 'Anandhi', 'Yogi Babu', 'Lijeesh', ...",Mari Selvaraj,A law student from a lower caste begins a frie...,A law student from a lower caste begins a frie...
...,...,...,...,...,...
245,24,"['Suriya', 'Samantha Ruth Prabhu', 'Nithya Men...",Vikram K. Kumar,"A scientist invents a time machine, which lead...","A scientist invents a time machine, which lead..."
246,Kapoor and Sons,"['Rishi Kapoor', 'Rajat Kapoor', 'Ratna Pathak...",Shakun Batra,The story about two brothers who visit their d...,The story about two brothers who visit their d...
247,Velaiilla Pattadhari,"['Dhanush', 'Saranya Ponvannan', 'Amala Paul',...",Velraj,A jobless young man gets to redeem himself.,A jobless young man gets to redeem himself.['D...
248,Colour Photo,"['Suhas', 'Chandini Chowdary', 'Sunil', 'Harsh...",Sandeep Raj,A tragic-comedy that is set in the 90s between...,A tragic-comedy that is set in the 90s between...
249,Rockstar,"['Ranbir Kapoor', 'Nargis Fakhri', 'Shammi Kap...",Imtiaz Ali,Janardhan Jakhar chases his dreams of becoming...,Janardhan Jakhar chases his dreams of becoming...

In [19]:
new_data  = movies.drop(columns=['Description'])

In [20]:
new_data

,Title,Movie Cast,Director,tags
0,Anbe Sivam,"['Kamal Haasan', 'Madhavan', 'Kiran Rathod', '...",Sundar C.,"Two men, one young and arrogant, the other dam..."
1,Golmaal,"['Amol Palekar', 'Bindiya Goswami', 'Deven Ver...",Hrishikesh Mukherjee,A man's simple lie to secure his job escalates...
2,Jai Bhim,"['Suriya', 'Lijo Mol Jose', 'Manikandan K.', '...",T.J. Gnanavel,When a tribal man is arrested for a case of al...
3,Nayakan,"['Kamal Haasan', 'Saranya Ponvannan', 'Delhi G...",Mani Ratnam,A common man's struggles against a corrupt pol...
4,Pariyerum Perumal,"['Kathir', 'Anandhi', 'Yogi Babu', 'Lijeesh', ...",Mari Selvaraj,A law student from a lower caste begins a frie...
...,...,...,...,...
245,24,"['Suriya', 'Samantha Ruth Prabhu', 'Nithya Men...",Vikram K. Kumar,"A scientist invents a time machine, which lead..."
246,Kapoor and Sons,"['Rishi Kapoor', 'Rajat Kapoor', 'Ratna Pathak...",Shakun Batra,The story about two brothers who visit their d...
247,Velaiilla Pattadhari,"['Dhanush', 'Saranya Ponvannan', 'Amala Paul',...",Velraj,A jobless young man gets to redeem himself.['D...
248,Colour Photo,"['Suhas', 'Chandini Chowdary', 'Sunil', 'Harsh...",Sandeep Raj,A tragic-comedy that is set in the 90s between...
249,Rockstar,"['Ranbir Kapoor', 'Nargis Fakhri', 'Shammi Kap...",Imtiaz Ali,Janardhan Jakhar chases his dreams of becoming...

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
cv=CountVectorizer(max_features=10000, stop_words='english')

In [23]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [24]:
vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [25]:
vector.shape

(250, 5125)

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
similarity=cosine_similarity(vector)

In [28]:
similarity

array([[1.        , 0.        , 0.02441931, ..., 0.05847053, 0.        ,
        0.        ],
       [0.        , 1.        , 0.02299002, ..., 0.05504819, 0.        ,
        0.02051525],
       [0.02441931, 0.02299002, 1.        , ..., 0.0556846 , 0.02473853,
        0.02075243],
       ...,
       [0.05847053, 0.05504819, 0.0556846 , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.02473853, ..., 0.        , 1.        ,
        0.04415108],
       [0.        , 0.02051525, 0.02075243, ..., 0.        , 0.04415108,
        1.        ]])

In [26]:
new_data[new_data['title']=="The Godfather"].index[0]

2

In [30]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].Title)

Jai Bhim
Bommarillu
Soodhu Kavvum
Dhuruvangal Pathinaaru
Athadu

In [31]:
def recommand(movies):
    index=new_data[new_data['Title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].Title)

In [32]:
recommand("Vikram")

Vikram
Unnaipol Oruvan
96
Super Deluxe
Jai Bhim

In [33]:
import pickle

In [34]:
pickle.dump(new_data, open('C:\mini_proj\Movies_Rec\movies_list.pkl', 'wb'))

In [35]:
pickle.dump(similarity, open('C:\mini_proj\Movies_Rec\similarity.pkl', 'wb'))

In [37]:
pickle.load(open('C:\mini_proj\Movies_Rec\movies_list.pkl', 'rb'))

,Title,Movie Cast,Director,tags
0,Anbe Sivam,"['Kamal Haasan', 'Madhavan', 'Kiran Rathod', '...",Sundar C.,"Two men, one young and arrogant, the other dam..."
1,Golmaal,"['Amol Palekar', 'Bindiya Goswami', 'Deven Ver...",Hrishikesh Mukherjee,A man's simple lie to secure his job escalates...
2,Jai Bhim,"['Suriya', 'Lijo Mol Jose', 'Manikandan K.', '...",T.J. Gnanavel,When a tribal man is arrested for a case of al...
3,Nayakan,"['Kamal Haasan', 'Saranya Ponvannan', 'Delhi G...",Mani Ratnam,A common man's struggles against a corrupt pol...
4,Pariyerum Perumal,"['Kathir', 'Anandhi', 'Yogi Babu', 'Lijeesh', ...",Mari Selvaraj,A law student from a lower caste begins a frie...
...,...,...,...,...
245,24,"['Suriya', 'Samantha Ruth Prabhu', 'Nithya Men...",Vikram K. Kumar,"A scientist invents a time machine, which lead..."
246,Kapoor and Sons,"['Rishi Kapoor', 'Rajat Kapoor', 'Ratna Pathak...",Shakun Batra,The story about two brothers who visit their d...
247,Velaiilla Pattadhari,"['Dhanush', 'Saranya Ponvannan', 'Amala Paul',...",Velraj,A jobless young man gets to redeem himself.['D...
248,Colour Photo,"['Suhas', 'Chandini Chowdary', 'Sunil', 'Harsh...",Sandeep Raj,A tragic-comedy that is set in the 90s between...
249,Rockstar,"['Ranbir Kapoor', 'Nargis Fakhri', 'Shammi Kap...",Imtiaz Ali,Janardhan Jakhar chases his dreams of becoming...